### ISSUE TITLE
standard-markdown

### ISSUE THREAD

**Issue by zeke** [feross/awesome-standard#7]
https://github.com/zeke/standard-markdown works just like `standard`, but instead of linting javascript files, it lints GitHub-Flavored `js` and `javascript` code blocks inside markdown files.

Is it awesome? I think so.

Where should it go in the README?

**Comment by Flet** [comment]
Whoa this is cool :)

**Comment by Flet** [comment]
Maybe build tools?

**Comment by feross** [comment]
👍 👍 👍 Cool package.

Build tools sounds good to me. Or we can make another section for "related projects" where things like `standard-readme` can go.

**Comment by feross** [comment]
@zeke Send a PR!
